PACKAGE_NAME="t2smp"
PACKAGE_VERSION="0.1"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build KVER=${kernelver}"

BUILT_MODULE_NAME[0]="t2smp"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"
