PACKAGE_NAME="apfs"
PACKAGE_VERSION="0.3.20"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build KERNEL_DIR=/lib/modules/${kernelver}/build KERNELRELEASE=${kernelver}"

BUILT_MODULE_NAME[0]="apfs"
DEST_MODULE_LOCATION[0]="/updates/dkms"

PRE_BUILD="genver.sh"

AUTOINSTALL="yes"
